feat(review-app-vercel): add new review app bot for vercel
p3ol/hypnobots pull request #296
Opened 2023-02-22 14:06 UTC by yannispgs

This is an alternative to the Review App in Heroku.

It setups the Environment Variables and Domain of a Vercel Project to ensure each PR has its proper HTTP URL for Preview. This URL will not change until the PR is closed. This bot also understand the existing `@review rebuild` and `@review <other_repo> #<pr>` commands for Vercel.

2023-02-23 07:19 UTC, dackmin requested changes

2023-02-23 07:19 UTC, dackmin commented on bots/review-app-vercel/utils.js
> +  const envs = [];
```js
const envs = Object.entries(env).map(([key, value]) => ({
  key,
  value,
  type: 'encrypted',
  target: ['preview'],
  gitBranch: ref,
}));

2023-02-23 07:19 UTC, dackmin commented on bots/review-app-vercel/utils.js
> +  const existingEnvVarsIds = existingEnvVars.map(o => o.id);
```js
try {
  await Promise.all(existingEnvVars.map(o =>
    queryApi('DELETE', `v9/projects/${repo}/env/${o.id}`)
  ));
} catch (e) {
  ...
}
```

2023-02-23 07:19 UTC, dackmin commented on bots/review-app-vercel/index.js
> +  regex: /^@review (.*) #(\d*)/,
`@review` might collide with the heroku bot if both are setup on the same repo (for obscure reasons). If we can't find a less generic, unused and more original name for this one, like `@rercel` (or `@megatron-annihilator-9000` for the creative minds out there), let it be `@review`.

2023-02-23 08:26 UTC, yannispgs commented on bots/review-app-vercel/index.test.js
> +      fetchMock
I tried with nock only by using `nock('https://api.vercel.com')` but it did not work at all. I could not catch any of the calls to the Vercel API with nock. I tried to use the `nock.recorder.rec()` to check whether the URLs and paths i was using were right. However, I never managed to print the calls to the Vercel API with it : only the Github calls were printed.

In the end, it seems that fetch cannot be caught with nock in node 18 ([forum post](https://stackoverflow.com/questions/74656122/how-do-i-mock-node-js-fetch-http-requests-responses-in-node-18)). It may work if I was using the `node-fetch` library instead of the global Node 18 implementation, but as `fetch` is now included in Node 18, I don't like the idea to use an older implementation.

2023-02-23 08:46 UTC, yannispgs commented on bots/review-app-vercel/index.test.js
> +      log: pino(streamLogsToOutput),
It is needed to parse the logs emitted during the probot run. I wanted to pass a mocked logger to the Probot constructor in order to check every calls content, but never managed to pass a Logger or console instance without having probot failing.

In the [official Probot doc](https://probot.github.io/docs/testing/#testing-log-output), the only way to catch the logs seems to overwrite the default Probot logger, which is a pino instance.

I could test the "config missing or ill-formed" path without parsing the logs (based on Github calls), as previously done. Catching pino logs allows a much better understanding of what is expected to happen, and to avoid false positive tests when we update the Github calls order.

2023-02-23 09:05 UTC, yannispgs commented on bots/review-app-vercel/index.js
> +  regex: /^@review (.*) #(\d*)/,
The Heroku Review Apps are similar to Vercel Previews, so `@preview` should suit

2023-02-23 10:43 UTC, yannispgs commented on bots/review-app-vercel/index.test.js
> +      fetchMock
If having both nock and fetchMock is an issue, I can replace fetch by the `https` module or something else, but that require some changes

2023-02-28 13:58 UTC, yannispgs commented on bots/review-app-vercel/index.test.js
> +      log: pino(streamLogsToOutput),
Agreed to use pino in pm

2023-02-28 13:58 UTC, yannispgs commented on bots/review-app-vercel/index.test.js
> +      fetchMock
Replaced fetch by node-fetch

2023-03-07 08:16 UTC, dackmin approved these changes

2023-03-08 14:58 UTC, merged